"""create users table

Revision ID: ba30ded44775
Revises: 
Create Date: 2025-05-09 18:42:08.971325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba30ded44775'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('discordid', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('discordid')
    )
    op.create_table('apelidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apelido', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('disponibilidade', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.discordid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apelidos')
    op.drop_table('users')
    # ### end Alembic commands ###
